frontend/controllers/IceController.php
<?php

namespace frontend\controllers;

use Yii;
use backend\models\Goods;
use backend\models\Ice;
use frontend\models\Card;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 *
 *   icecontroller from frontend side
 *
 */
    class IceController extends \yii\web\Controller
    {
        public function behaviors()
        {
            return [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'actions' => ['login', 'error'],
                            'allow' => true,
                        ],
                        [
                            'actions' => ['logout', 'store', 'choice', 'card'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'logout' => ['post'],
                    ],
                ],
            ];
        }

        public function actions()
        {
            return [
                'error' => [
                    'class' => 'yii\web\ErrorAction',
                ],
            ];
        }

        /**
         *
         *   сдесь нужно вывести все мороженное в красивом виде
         *
         */
        public function actionStore()
        {
            $altay = Ice::findOne(1);
            $ananas = Ice::findOne(2);
            $arbuz = Ice::findOne(3);
            $bablgam = Ice::findOne(4);
            $banab = Ice::findOne(5);
            $basliyskoeMango = Ice::findOne(6);
            $belgiyskiyChocolate = Ice::findOne(7);
            $blueNebo = Ice::findOne(8);
            $fistashki = Ice::findOne(9);
            $franceKremBrule = Ice::findOne(10);
            $greenMatya = Ice::findOne(11);
            $ispanskayaKlubnika = Ice::findOne(12);
            $kivi = Ice::findOne(13);
            $limon = Ice::findOne(14);
            $marokanskiyApelsin = Ice::findOne(15);

                
            return $this->render('store', [
                'altay' => $altay,
                'ananas' => $ananas,
                'arbuz' => $arbuz,
                'bablgam' => $bablgam,
                'banab' => $banab,
                'basliyskoeMango' => $basliyskoeMango,
                'belgiyskiyChocolate' => $belgiyskiyChocolate,
                'blueNebo' => $blueNebo,
                'fistashki' => $fistashki,
                'franceKremBrule' => $franceKremBrule,
                'greenMatya' => $greenMatya,
                'ispanskayaKlubnika' => $ispanskayaKlubnika,
                'kivi' => $kivi,
                'limon' => $limon,
                'marokanskiyApelsin' => $marokanskiyApelsin,                
            ]);
        }

        /**
         *
         *   выбор мороженного принимает идентификатор товара из Базы Данных
         *   отправляет в отдел вью для выбора нужно выбрать количество мороженного
         */
        public function actionChoice($id)
        {
            $ices = Ice::find()->all();
            $ice = Ice::findOne($id);
            $card = Yii::$app -> card;

            /**
             *
             *   скриптик который принимает $id и в зависимости от того какой это номер (они от 1 до 15 могут быть)
             *   переменной $img присваивается название jpg file - и затем вызывается это изображение с хранилища изображений
             */
            switch($id)
            {
            case 1:
                $img = 'oblepiha.jpg';
                break;
            case 2:
                $img = 'chance_ananas.jpg';
                break;
            case 3:
                $img = 'choice_arbuz.jpg';
                break;
            case 4:
                $img = 'change_bablgam.jpg';
                break;
            case 5:
                $img = 'change_banan.jpg';
                break;
            case 6:
                $img = 'change_basliyskoeMango.jpg';
                break;
            case 7:
                $img = 'change_belgiyskiyChocolate.jpg';
                break;
            case 8:
                $img = 'change_blueNebo.jpg';
                break;
            case 9:
                $img = 'change_fistashki.jpg';
                break;
            case 10:
                $img = 'change_franceKremBrule.jpg';
                break;
            case 11:
                $img = 'change_greenMatya.jpg';
                break;
            case 12:
                $img = 'change_ispanskayaKlubnika.jpg';
                break;
            case 13:
                $img = 'kivi.jpg';
                break;
            case 14:
                $img = 'limon.jpg';
                break;
            case 15:
                $img = 'marokanskiyApelsin.jpg';
                break;
            default:
                echo 'default';
            }
            
            return $this->render('choice', [
                'id' => $id,
                'ice' => $ice,
                'card' => $card,
                'ices' => $ices,
                'img' => $img,
            ]);

        }
    }

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\assets\BaseAsset;
use common\widgets\Alert;
use backend\models\Telephone;
AppAsset::register($this);
BaseAsset::register($this);

$address = Telephone::findOne(1);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
<meta charset="<?= Yii::$app->charset ?>">
<?php $this->registerCsrfMetaTags() ?>
<title><?= Html::encode($this->title) ?></title>
<?php $this->head() ?>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Free HTML Templates" name="keywords">
<meta content="Free HTML Templates" name="description">

<!-- Favicon -->


<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">


<!-- Font Awesome -->


<!-- Libraries Stylesheet -->



<!-- Customized Bootstrap Stylesheet -->

</head>

<body>
    <?php $this->beginBody() ?>
    <?php  
    NavBar::begin([
	'brandLabel' =>  Html::img('@web/user_img/logo.jpg'),
	'brandUrl' => Yii::$app->homeUrl,
	'options' => [
            'class' => '"navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0"',
	],
    ]);
    
    $menuItems = [
	['label' => 'Купить', 'url' => ['/ice/store']],
	['label' => 'О нас', 'url' => ['/site/index']],
	['label' => 'Контакты', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
	$menuItems[] = ['label' => 'Регистрация', 'url' => ['/site/signup']];
	$menuItems[] = ['label' => 'Войти', 'url' => ['/site/login']];
    } else {
	$menuItems[] = '<li>'
                     . Html::beginForm(['/site/logout'], 'post')
                     . Html::submitButton(
			 'Выйти (' . Yii::$app->user->identity->username . ')',
			 ['class' => 'nav-link']
                     )
                     . Html::endForm()
                     . '</li>';
    }
    echo Nav::widget([
	'options' => ['class' => 'navbar-nav ml-auto py-0'],
	'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <a href="" class="navbar-brand d-block d-lg-none">
	<h1 class="m-0 display-4 text-primary"><span class="text-secondary">i</span>lmiojelato</h1>
    </a>

    <!-- Topbar Start -->
    <div class="container-fluid bg-primary py-3 d-none d-md-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white pr-3" href="">FAQs</a>
                        <span class="text-white">|</span>
                        <a class="text-white px-3" href="">Help</a>
                        <span class="text-white">|</span>
                        <a class="text-white pl-3" href="">Support</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>


    <!-- Footer Start -->
    <div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
        <div class="container text-center py-5">
            <div class="row">
                <div class="col-12 mb-4">
                    <a href="index.php" class="navbar-brand m-0">
                        <h1 class="m-0 mt-n2 display-4 text-primary"><span class="text-secondary">i</span>lmiojelato</h1>
                    </a>
                </div>
                <div class="col-12 mb-4">
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
                </div>
                <div class="col-12 mt-2 mb-4">
                    <div class="row">
                        <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                            <h5 class="font-weight-bold mb-2">Контакты:</h5>
                            <p class="mb-2"></p>
                            <p class="mb-0">+7<?= $address -> telephone  ?></p>
                        </div>
                        <div class="col-sm-6 text-center text-sm-left">
                            <h5 class="font-weight-bold mb-2">Часы работы</h5>
                            <p class="mb-2">Пн – Вс, 8 утра – 9 вечера</p>
                            <p class="mb-0"></p>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <p class="m-0">&copy;<?= Html::encode(Yii::$app -> name)  ?><?= date('Y')  ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-secondary px-2 back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->

    <!-- Contact Javascript File -->

    <!-- Template Javascript -->
<?php $this->endBody() ?>


</html>
<?php $this->endPage() ?>